version: '3'

services:
  api_gateway:
    image: 'api-gateway:latest'
    container_name: "api_gateway"
    env_file: .env
    volumes:
      - './conf:/usr/local/openresty/nginx/conf'
      - './logs:/usr/local/openresty/nginx/logs'
      - './lua:/usr/local/openresty/nginx/lua'
    ports:
      - 8080:8080

networks:
  default:
    name: sportiq
    external: true
